# HIT Spider
Init

In [1]:
import sys
import os
# Directory Management
try:
    # Run in Terminal
    ROOT_DIR = os.path.dirname(os.path.abspath(__file__))
except:
    # Run in ipykernel & interactive
    ROOT_DIR = os.getcwd()
if ".." not in sys.path:
    sys.path.append("..")

from fast_legged_planner_py.robot_interface.hitspider_robotinterface import HITSpider_RobotInterface, FOOT_LINK_NAME
from fast_legged_planner_py.robot_interface.pin_IK import pinIK
import pinocchio as pin
import numpy as np


urdf_file = os.path.join(os.path.dirname(ROOT_DIR), "model", "hit_spider", "urdf", "ElSpider.urdf")
pack_dirs = [os.path.dirname(os.path.dirname(ROOT_DIR))]
hit_spider = HITSpider_RobotInterface(urdf_file, pack_dirs)


/home/yip/miniconda3/envs/robotic_course/lib/python3.9/site-packages/scipy/__init__.py:132: UserWarning: A NumPy version >=1.21.6 and <1.28.0 is required for this version of SciPy (detected version 1.21.0)
  warnings.warn(f"A NumPy version >={np_minversion} and <{np_maxversion}"


You can open the visualizer by visiting the following URL:
http://127.0.0.1:7000/static/


In [2]:
# Collision Model
# hit_spider.print_frames()
# hit_spider.print_joints()

# hit_spider.get_frameid(FOOT_LINK_NAME[2])

In [10]:
# Display
q0 = hit_spider.robot.q0
q_leg = [-2.56, -2.11, -0.484]
q = hit_spider.get_full_q(q_leg, 0)
hit_spider.viz.display(q)
# hit_spider.vis_collision_model(q0)
for link in FOOT_LINK_NAME:
    print(hit_spider.get_frame_placement(q0,link).translation)
# hit_spider.robot.computeFrameJacobian
# print(hit_spider.robot.data.oMi[3].translation)

[-0.54        0.93529727 -0.5       ]
[-0.54       -0.93529727 -0.5       ]
[-1.08000000e+00  5.01820807e-16 -5.00000000e-01]
[ 0.54        0.93529727 -0.5       ]
[ 0.54       -0.93529727 -0.5       ]
[ 1.08000000e+00 -1.99840144e-16 -5.00000000e-01]


In [3]:
# Inverse Kenematics
leg_num = 0
q_leg = hit_spider.IK_foot(leg_num, np.array([0.1, 0.1, 0.1]))
print(q_leg)
hit_spider.viz.display(hit_spider.get_full_q(q_leg,leg_num))

target_list = [np.array([0, 0, -5]) for i in range(6)]
q = hit_spider.IK_foots(target_list)
hit_spider.viz.display(q)

[ 0.35961642 -2.36002921 -0.34080559]


array([-1.,  1., -1.])